### ISSUE TITLE
got error on centos 5

### ISSUE THREAD

**Issue by w58850** [zsky/sslstrip#2]
# node index.js
/tmp/sslstrip-master/index.js:7
class ProxyServer {
^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by zsky** [comment]
node 版本不对吧？不支持 class？
